import katex from "katex";
import { marked } from "marked";

import { htmlHost, registerRenderer } from "@spaceterm/block-renderer";
import type { TrustTier } from "@spaceterm/block-renderer";

// ========================================================================
// Registration
// ========================================================================

/// Register the heavy renderers into `@spaceterm/block-renderer`'s registry. The host
/// (VSCode webview, native shell) calls this once at startup; `block-renderer`
/// itself stays free of these dependencies.
export function registerRichRenderers(): void {
  registerRenderer("text/latex", renderLatex);
  registerRenderer("text/markdown", renderMarkdown);
}

// ========================================================================
// Renderers
// ========================================================================

// KaTeX output is generated by us (no user scripts), so it is safe to inline.
function renderLatex(
  value: unknown,
  _trust: TrustTier,
  doc: Document,
): HTMLElement {
  const host = doc.createElement("span");
  host.className = "spaceterm-latex";
  host.innerHTML = katex.renderToString(asText(value), {
    throwOnError: false,
    displayMode: true,
  });
  return host;
}

// Markdown can embed arbitrary HTML, so the rendered output is sandboxed by trust
// tier through block-renderer's `htmlHost` rather than inlined directly.
function renderMarkdown(
  value: unknown,
  trust: TrustTier,
  doc: Document,
): HTMLElement {
  // `async: false` guarantees a string at runtime; narrow it for the type system.
  const rendered = marked.parse(asText(value), { async: false });
  const html = typeof rendered === "string" ? rendered : "";
  return htmlHost(html, trust, doc);
}

function asText(value: unknown): string {
  return typeof value === "string" ? value : String(value);
}
